### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by kyadav271099** [ducthanh98/dawn-validator#1]
Error: error:1C80006B:Provider routines::wrong final block length\"}"} have this error

**Comment by ducthanh98** [comment]
Can you provide an image or the full log about this?

Note: The current version now uses a bearer token instead of a password. I forgot to update the README and config example. If you are currently using a password, you can try using a token instead.

**Comment by kyadav271099** [comment]
> Can you provide an image or the full log about this?
> 
> Note: The current version now uses a bearer token instead of a password. I forgot to update the README and config example. If you are currently using a password, you can try using a token instead.



> Can you provide an image or the full log about this?
> 
> Note: The current version now uses a bearer token instead of a password. I forgot to update the README and config example. If you are currently using a password, you can try using a token instead.

thanks for help working 😃
