### ISSUE TITLE
error this acc

### ISSUE THREAD

**Issue by kyadav271099** [ducthanh98/dawn-validator#3]
![Screenshot_2024-09-10-08-17-55-069_com termux](https://github.com/user-attachments/assets/f931b20c-a77c-4469-af54-99dc62731492)
other working but not this one have solution ?

**Comment by ducthanh98** [comment]
Have you tried another proxy?

**Comment by kyadav271099** [comment]
yes i changed proxy still same error don't know why 

edit i solved problem by changing port
